/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class StateDSLUiModule extends AbstractStateDSLUiModule {
  public StateDSLUiModule(final AbstractUIPlugin plugin) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe type StateDSLUiModule is already defined in StateDSLUiModule.java.");
  }
}
