/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.statedsl.ui.internal.StatedslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class StateDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(StatedslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		StatedslActivator activator = StatedslActivator.getInstance();
		return activator != null ? activator.getInjector(StatedslActivator.ORG_XTEXT_EXAMPLE_STATEDSL_STATEDSL) : null;
	}

}
