/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.example.statedsl.StateDSLRuntimeModule
import org.xtext.example.statedsl.StateDSLStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class StateDSLIdeSetup extends StateDSLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new StateDSLRuntimeModule, new StateDSLIdeModule))
	}
	
}
