/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl.ide;

import org.eclipse.xtext.util.Modules2;
import org.xtext.example.statedsl.StateDSLRuntimeModule;
import org.xtext.example.statedsl.StateDSLStandaloneSetup;

import com.google.inject.Guice;
import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class StateDSLIdeSetup extends StateDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new StateDSLRuntimeModule(), new StateDSLIdeModule()));
	}
	
}
