/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class StateDSLIdeModule extends AbstractStateDSLIdeModule {
}
