/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl.ide;

import org.eclipse.xtext.util.Modules2;
import org.xtext.example.statedsl.StateDSLRuntimeModule;
import org.xtext.example.statedsl.StateDSLStandaloneSetup;

import com.google.inject.Guice;
import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class StateDSLIdeSetup extends StateDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    StateDSLRuntimeModule _stateDSLRuntimeModule = new StateDSLRuntimeModule();
    StateDSLIdeModule _stateDSLIdeModule = new StateDSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_stateDSLRuntimeModule, _stateDSLIdeModule));
  }
}
