/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class StateDSLGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class DomainmodelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.statedsl.StateDSL.Domainmodel");
		private final Assignment cElementsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cElementsStateMachineParserRuleCall_0 = (RuleCall)cElementsAssignment.eContents().get(0);
		
		//Domainmodel:
		//    elements+=(StateMachine)*;
		@Override public ParserRule getRule() { return rule; }
		
		//elements+=(StateMachine)*
		public Assignment getElementsAssignment() { return cElementsAssignment; }
		
		//(StateMachine)
		public RuleCall getElementsStateMachineParserRuleCall_0() { return cElementsStateMachineParserRuleCall_0; }
	}
	public class StateMachineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.statedsl.StateDSL.StateMachine");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStateMachineKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cStatesKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cEqualsSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftSquareBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cStatesAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cStatesAStateParserRuleCall_6_0 = (RuleCall)cStatesAssignment_6.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cTransitionsKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cEqualsSignKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cLeftSquareBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cTransitionsAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cTransitionsTransitionParserRuleCall_12_0 = (RuleCall)cTransitionsAssignment_12.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cCommaKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cStartKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Keyword cEqualsSignKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Assignment cStartAssignment_17 = (Assignment)cGroup.eContents().get(17);
		private final RuleCall cStartStateParserRuleCall_17_0 = (RuleCall)cStartAssignment_17.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_18 = (Keyword)cGroup.eContents().get(18);
		
		//StateMachine:
		//    'StateMachine' name=ID '{'
		//        'states' '=' '[' states+=(AState)+ ']' ','
		//        'transitions' '=' '[' transitions+=(Transition)* ']' ','
		//        'start' '=' start=State
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'StateMachine' name=ID '{'
		//    'states' '=' '[' states+=(AState)+ ']' ','
		//    'transitions' '=' '[' transitions+=(Transition)* ']' ','
		//    'start' '=' start=State
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'StateMachine'
		public Keyword getStateMachineKeyword_0() { return cStateMachineKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'states'
		public Keyword getStatesKeyword_3() { return cStatesKeyword_3; }
		
		//'='
		public Keyword getEqualsSignKeyword_4() { return cEqualsSignKeyword_4; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_5() { return cLeftSquareBracketKeyword_5; }
		
		//states+=(AState)+
		public Assignment getStatesAssignment_6() { return cStatesAssignment_6; }
		
		//(AState)
		public RuleCall getStatesAStateParserRuleCall_6_0() { return cStatesAStateParserRuleCall_6_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_7() { return cRightSquareBracketKeyword_7; }
		
		//','
		public Keyword getCommaKeyword_8() { return cCommaKeyword_8; }
		
		//'transitions'
		public Keyword getTransitionsKeyword_9() { return cTransitionsKeyword_9; }
		
		//'='
		public Keyword getEqualsSignKeyword_10() { return cEqualsSignKeyword_10; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_11() { return cLeftSquareBracketKeyword_11; }
		
		//transitions+=(Transition)*
		public Assignment getTransitionsAssignment_12() { return cTransitionsAssignment_12; }
		
		//(Transition)
		public RuleCall getTransitionsTransitionParserRuleCall_12_0() { return cTransitionsTransitionParserRuleCall_12_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_13() { return cRightSquareBracketKeyword_13; }
		
		//','
		public Keyword getCommaKeyword_14() { return cCommaKeyword_14; }
		
		//'start'
		public Keyword getStartKeyword_15() { return cStartKeyword_15; }
		
		//'='
		public Keyword getEqualsSignKeyword_16() { return cEqualsSignKeyword_16; }
		
		//start=State
		public Assignment getStartAssignment_17() { return cStartAssignment_17; }
		
		//State
		public RuleCall getStartStateParserRuleCall_17_0() { return cStartStateParserRuleCall_17_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_18() { return cRightCurlyBracketKeyword_18; }
	}
	public class AStateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.statedsl.StateDSL.AState");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cStateParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cStateMachineParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//AState:
		//    State | StateMachine
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//State | StateMachine
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//State
		public RuleCall getStateParserRuleCall_0() { return cStateParserRuleCall_0; }
		
		//StateMachine
		public RuleCall getStateMachineParserRuleCall_1() { return cStateMachineParserRuleCall_1; }
	}
	public class StateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.statedsl.StateDSL.State");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//State:
		//   'State' name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//'State' name=ID
		public Group getGroup() { return cGroup; }
		
		//'State'
		public Keyword getStateKeyword_0() { return cStateKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class TransitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.statedsl.StateDSL.Transition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTransitionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cFromKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cEqualsSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cFromAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cFromAStateParserRuleCall_5_0 = (RuleCall)cFromAssignment_5.eContents().get(0);
		private final Keyword cToKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cEqualsSignKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cToAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cToAStateParserRuleCall_8_0 = (RuleCall)cToAssignment_8.eContents().get(0);
		private final Keyword cConditionKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cEqualsSignKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cConditionAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cConditionConditionParserRuleCall_11_0 = (RuleCall)cConditionAssignment_11.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Transition:
		//    'Transition' name=ID '{'
		//        'from' '=' from=AState
		//        'to' '=' to=AState
		//        'condition' '=' condition=Condition
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Transition' name=ID '{'
		//    'from' '=' from=AState
		//    'to' '=' to=AState
		//    'condition' '=' condition=Condition
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Transition'
		public Keyword getTransitionKeyword_0() { return cTransitionKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'from'
		public Keyword getFromKeyword_3() { return cFromKeyword_3; }
		
		//'='
		public Keyword getEqualsSignKeyword_4() { return cEqualsSignKeyword_4; }
		
		//from=AState
		public Assignment getFromAssignment_5() { return cFromAssignment_5; }
		
		//AState
		public RuleCall getFromAStateParserRuleCall_5_0() { return cFromAStateParserRuleCall_5_0; }
		
		//'to'
		public Keyword getToKeyword_6() { return cToKeyword_6; }
		
		//'='
		public Keyword getEqualsSignKeyword_7() { return cEqualsSignKeyword_7; }
		
		//to=AState
		public Assignment getToAssignment_8() { return cToAssignment_8; }
		
		//AState
		public RuleCall getToAStateParserRuleCall_8_0() { return cToAStateParserRuleCall_8_0; }
		
		//'condition'
		public Keyword getConditionKeyword_9() { return cConditionKeyword_9; }
		
		//'='
		public Keyword getEqualsSignKeyword_10() { return cEqualsSignKeyword_10; }
		
		//condition=Condition
		public Assignment getConditionAssignment_11() { return cConditionAssignment_11; }
		
		//Condition
		public RuleCall getConditionConditionParserRuleCall_11_0() { return cConditionConditionParserRuleCall_11_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class ConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.statedsl.StateDSL.Condition");
		private final RuleCall cOrConditionParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Condition:
		//    OrCondition
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//OrCondition
		public RuleCall getOrConditionParserRuleCall() { return cOrConditionParserRuleCall; }
	}
	public class OrConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.statedsl.StateDSL.OrCondition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cAndConditionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cOrConditionLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cORKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightAndConditionParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//OrCondition returns Condition:
		//    AndCondition ({OrCondition.left=current} 'OR' right=AndCondition)*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//AndCondition ({OrCondition.left=current} 'OR' right=AndCondition)*
		public Group getGroup() { return cGroup; }
		
		//AndCondition
		public RuleCall getAndConditionParserRuleCall_0() { return cAndConditionParserRuleCall_0; }
		
		//({OrCondition.left=current} 'OR' right=AndCondition)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{OrCondition.left=current}
		public Action getOrConditionLeftAction_1_0() { return cOrConditionLeftAction_1_0; }
		
		//'OR'
		public Keyword getORKeyword_1_1() { return cORKeyword_1_1; }
		
		//right=AndCondition
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//AndCondition
		public RuleCall getRightAndConditionParserRuleCall_1_2_0() { return cRightAndConditionParserRuleCall_1_2_0; }
	}
	public class AndConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.statedsl.StateDSL.AndCondition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cPrimaryConditionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cAndConditionLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cANDKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightPrimaryConditionParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//AndCondition returns Condition:
		//    PrimaryCondition ({AndCondition.left=current} 'AND' right=PrimaryCondition)*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//PrimaryCondition ({AndCondition.left=current} 'AND' right=PrimaryCondition)*
		public Group getGroup() { return cGroup; }
		
		//PrimaryCondition
		public RuleCall getPrimaryConditionParserRuleCall_0() { return cPrimaryConditionParserRuleCall_0; }
		
		//({AndCondition.left=current} 'AND' right=PrimaryCondition)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{AndCondition.left=current}
		public Action getAndConditionLeftAction_1_0() { return cAndConditionLeftAction_1_0; }
		
		//'AND'
		public Keyword getANDKeyword_1_1() { return cANDKeyword_1_1; }
		
		//right=PrimaryCondition
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//PrimaryCondition
		public RuleCall getRightPrimaryConditionParserRuleCall_1_2_0() { return cRightPrimaryConditionParserRuleCall_1_2_0; }
	}
	public class PrimaryConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.statedsl.StateDSL.PrimaryCondition");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cLiteralConditionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cConditionParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		
		//PrimaryCondition returns Condition:     // here when you are making your tree, you find out if the branch is done "lit-condition"
		//    LiteralCondition |                    // or is hiding a new branch in the ()  condition -> or-condition -> and-condition
		//    '(' Condition ')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		// // here when you are making your tree, you find out if the branch is done "lit-condition"
		//LiteralCondition |                    // or is hiding a new branch in the ()  condition -> or-condition -> and-condition
		//'(' Condition ')'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		// // here when you are making your tree, you find out if the branch is done "lit-condition"
		//LiteralCondition
		public RuleCall getLiteralConditionParserRuleCall_0() { return cLiteralConditionParserRuleCall_0; }
		
		//                // or is hiding a new branch in the ()  condition -> or-condition -> and-condition
		//'(' Condition ')'
		public Group getGroup_1() { return cGroup_1; }
		
		//                // or is hiding a new branch in the ()  condition -> or-condition -> and-condition
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//Condition
		public RuleCall getConditionParserRuleCall_1_1() { return cConditionParserRuleCall_1_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_2() { return cRightParenthesisKeyword_1_2; }
	}
	public class LiteralConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.statedsl.StateDSL.LiteralCondition");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//LiteralCondition returns Condition:     // X, Y, isReady :: type conditions, "singular" no and/or involved
		//    name = ID;
		@Override public ParserRule getRule() { return rule; }
		
		// // X, Y, isReady :: type conditions, "singular" no and/or involved
		//name = ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	
	
	private final DomainmodelElements pDomainmodel;
	private final StateMachineElements pStateMachine;
	private final AStateElements pAState;
	private final StateElements pState;
	private final TransitionElements pTransition;
	private final ConditionElements pCondition;
	private final OrConditionElements pOrCondition;
	private final AndConditionElements pAndCondition;
	private final PrimaryConditionElements pPrimaryCondition;
	private final LiteralConditionElements pLiteralCondition;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public StateDSLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pDomainmodel = new DomainmodelElements();
		this.pStateMachine = new StateMachineElements();
		this.pAState = new AStateElements();
		this.pState = new StateElements();
		this.pTransition = new TransitionElements();
		this.pCondition = new ConditionElements();
		this.pOrCondition = new OrConditionElements();
		this.pAndCondition = new AndConditionElements();
		this.pPrimaryCondition = new PrimaryConditionElements();
		this.pLiteralCondition = new LiteralConditionElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.statedsl.StateDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Domainmodel:
	//    elements+=(StateMachine)*;
	public DomainmodelElements getDomainmodelAccess() {
		return pDomainmodel;
	}
	
	public ParserRule getDomainmodelRule() {
		return getDomainmodelAccess().getRule();
	}
	
	//StateMachine:
	//    'StateMachine' name=ID '{'
	//        'states' '=' '[' states+=(AState)+ ']' ','
	//        'transitions' '=' '[' transitions+=(Transition)* ']' ','
	//        'start' '=' start=State
	//    '}';
	public StateMachineElements getStateMachineAccess() {
		return pStateMachine;
	}
	
	public ParserRule getStateMachineRule() {
		return getStateMachineAccess().getRule();
	}
	
	//AState:
	//    State | StateMachine
	//;
	public AStateElements getAStateAccess() {
		return pAState;
	}
	
	public ParserRule getAStateRule() {
		return getAStateAccess().getRule();
	}
	
	//State:
	//   'State' name=ID;
	public StateElements getStateAccess() {
		return pState;
	}
	
	public ParserRule getStateRule() {
		return getStateAccess().getRule();
	}
	
	//Transition:
	//    'Transition' name=ID '{'
	//        'from' '=' from=AState
	//        'to' '=' to=AState
	//        'condition' '=' condition=Condition
	//    '}';
	public TransitionElements getTransitionAccess() {
		return pTransition;
	}
	
	public ParserRule getTransitionRule() {
		return getTransitionAccess().getRule();
	}
	
	//Condition:
	//    OrCondition
	//;
	public ConditionElements getConditionAccess() {
		return pCondition;
	}
	
	public ParserRule getConditionRule() {
		return getConditionAccess().getRule();
	}
	
	//OrCondition returns Condition:
	//    AndCondition ({OrCondition.left=current} 'OR' right=AndCondition)*
	//;
	public OrConditionElements getOrConditionAccess() {
		return pOrCondition;
	}
	
	public ParserRule getOrConditionRule() {
		return getOrConditionAccess().getRule();
	}
	
	//AndCondition returns Condition:
	//    PrimaryCondition ({AndCondition.left=current} 'AND' right=PrimaryCondition)*
	//;
	public AndConditionElements getAndConditionAccess() {
		return pAndCondition;
	}
	
	public ParserRule getAndConditionRule() {
		return getAndConditionAccess().getRule();
	}
	
	//PrimaryCondition returns Condition:     // here when you are making your tree, you find out if the branch is done "lit-condition"
	//    LiteralCondition |                    // or is hiding a new branch in the ()  condition -> or-condition -> and-condition
	//    '(' Condition ')'
	//;
	public PrimaryConditionElements getPrimaryConditionAccess() {
		return pPrimaryCondition;
	}
	
	public ParserRule getPrimaryConditionRule() {
		return getPrimaryConditionAccess().getRule();
	}
	
	//LiteralCondition returns Condition:     // X, Y, isReady :: type conditions, "singular" no and/or involved
	//    name = ID;
	public LiteralConditionElements getLiteralConditionAccess() {
		return pLiteralCondition;
	}
	
	public ParserRule getLiteralConditionRule() {
		return getLiteralConditionAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
