/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.statedsl.ui.internal.StatedslActivator;

public class StateDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return StatedslActivator.getInstance().getInjector("org.xtext.example.statedsl.StateDSL");
	}

}
