/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl.validation;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class StateDSLValidator extends AbstractStateDSLValidator {
  public static final String INVALID_INHERITANCE = "invalidINHERITANCE";
}
