/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl.stateDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>And Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.statedsl.stateDSL.StateDSLPackage#getAndCondition()
 * @model
 * @generated
 */
public interface AndCondition extends Condition
{
} // AndCondition
