/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl.stateDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>State Machine</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.statedsl.stateDSL.StateMachine#getStates <em>States</em>}</li>
 *   <li>{@link org.xtext.example.statedsl.stateDSL.StateMachine#getTransitions <em>Transitions</em>}</li>
 *   <li>{@link org.xtext.example.statedsl.stateDSL.StateMachine#getStart <em>Start</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.statedsl.stateDSL.StateDSLPackage#getStateMachine()
 * @model
 * @generated
 */
public interface StateMachine extends AState
{
  /**
   * Returns the value of the '<em><b>States</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.statedsl.stateDSL.AState}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>States</em>' containment reference list.
   * @see org.xtext.example.statedsl.stateDSL.StateDSLPackage#getStateMachine_States()
   * @model containment="true"
   * @generated
   */
  EList<AState> getStates();

  /**
   * Returns the value of the '<em><b>Transitions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.statedsl.stateDSL.Transition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transitions</em>' containment reference list.
   * @see org.xtext.example.statedsl.stateDSL.StateDSLPackage#getStateMachine_Transitions()
   * @model containment="true"
   * @generated
   */
  EList<Transition> getTransitions();

  /**
   * Returns the value of the '<em><b>Start</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start</em>' containment reference.
   * @see #setStart(State)
   * @see org.xtext.example.statedsl.stateDSL.StateDSLPackage#getStateMachine_Start()
   * @model containment="true"
   * @generated
   */
  State getStart();

  /**
   * Sets the value of the '{@link org.xtext.example.statedsl.stateDSL.StateMachine#getStart <em>Start</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start</em>' containment reference.
   * @see #getStart()
   * @generated
   */
  void setStart(State value);

  

} // StateMachine
