/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl.stateDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>State</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.statedsl.stateDSL.StateDSLPackage#getState()
 * @model
 * @generated
 */
public interface State extends AState
{
} // State
