/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl.stateDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.statedsl.stateDSL.Transition#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.statedsl.stateDSL.Transition#getFrom <em>From</em>}</li>
 *   <li>{@link org.xtext.example.statedsl.stateDSL.Transition#getTo <em>To</em>}</li>
 *   <li>{@link org.xtext.example.statedsl.stateDSL.Transition#getCondition <em>Condition</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.statedsl.stateDSL.StateDSLPackage#getTransition()
 * @model
 * @generated
 */
public interface Transition extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.statedsl.stateDSL.StateDSLPackage#getTransition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.statedsl.stateDSL.Transition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>From</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From</em>' containment reference.
   * @see #setFrom(State)
   * @see org.xtext.example.statedsl.stateDSL.StateDSLPackage#getTransition_From()
   * @model containment="true"
   * @generated
   */
  State getFrom();

  /**
   * Sets the value of the '{@link org.xtext.example.statedsl.stateDSL.Transition#getFrom <em>From</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From</em>' containment reference.
   * @see #getFrom()
   * @generated
   */
  void setFrom(State value);

  /**
   * Returns the value of the '<em><b>To</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' containment reference.
   * @see #setTo(State)
   * @see org.xtext.example.statedsl.stateDSL.StateDSLPackage#getTransition_To()
   * @model containment="true"
   * @generated
   */
  State getTo();

  /**
   * Sets the value of the '{@link org.xtext.example.statedsl.stateDSL.Transition#getTo <em>To</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To</em>' containment reference.
   * @see #getTo()
   * @generated
   */
  void setTo(State value);

  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Condition)
   * @see org.xtext.example.statedsl.stateDSL.StateDSLPackage#getTransition_Condition()
   * @model containment="true"
   * @generated
   */
  Condition getCondition();

  /**
   * Sets the value of the '{@link org.xtext.example.statedsl.stateDSL.Transition#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Condition value);

} // Transition
