/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class StateDSLUiModule extends AbstractStateDSLUiModule {

	public StateDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
