/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class StateDSLStandaloneSetup extends StateDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new StateDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
