/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.statedsl.ide.contentassist.antlr.internal.InternalStateDSLParser;
import org.xtext.example.statedsl.services.StateDSLGrammarAccess;

public class StateDSLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(StateDSLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, StateDSLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getAStateAccess().getAlternatives(), "rule__AState__Alternatives");
			builder.put(grammarAccess.getStateMachineAccess().getGroup(), "rule__StateMachine__Group__0");
			builder.put(grammarAccess.getStateAccess().getGroup(), "rule__State__Group__0");
			builder.put(grammarAccess.getConditionAccess().getGroup(), "rule__Condition__Group__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup(), "rule__Transition__Group__0");
			builder.put(grammarAccess.getDomainmodelAccess().getElementsAssignment(), "rule__Domainmodel__ElementsAssignment");
			builder.put(grammarAccess.getStateMachineAccess().getNameAssignment_1(), "rule__StateMachine__NameAssignment_1");
			builder.put(grammarAccess.getStateMachineAccess().getStatesAssignment_6(), "rule__StateMachine__StatesAssignment_6");
			builder.put(grammarAccess.getStateMachineAccess().getTransitionsAssignment_12(), "rule__StateMachine__TransitionsAssignment_12");
			builder.put(grammarAccess.getStateMachineAccess().getStartAssignment_17(), "rule__StateMachine__StartAssignment_17");
			builder.put(grammarAccess.getStateAccess().getNameAssignment_1(), "rule__State__NameAssignment_1");
			builder.put(grammarAccess.getConditionAccess().getNameAssignment_1(), "rule__Condition__NameAssignment_1");
			builder.put(grammarAccess.getTransitionAccess().getNameAssignment_1(), "rule__Transition__NameAssignment_1");
			builder.put(grammarAccess.getTransitionAccess().getFromAssignment_5(), "rule__Transition__FromAssignment_5");
			builder.put(grammarAccess.getTransitionAccess().getToAssignment_8(), "rule__Transition__ToAssignment_8");
			builder.put(grammarAccess.getTransitionAccess().getConditionAssignment_11(), "rule__Transition__ConditionAssignment_11");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private StateDSLGrammarAccess grammarAccess;

	@Override
	protected InternalStateDSLParser createParser() {
		InternalStateDSLParser result = new InternalStateDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public StateDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(StateDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
