/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.statedsl.services.StateDSLGrammarAccess;
import org.xtext.example.statedsl.stateDSL.AndCondition;
import org.xtext.example.statedsl.stateDSL.Condition;
import org.xtext.example.statedsl.stateDSL.Domainmodel;
import org.xtext.example.statedsl.stateDSL.OrCondition;
import org.xtext.example.statedsl.stateDSL.State;
import org.xtext.example.statedsl.stateDSL.StateDSLPackage;
import org.xtext.example.statedsl.stateDSL.StateMachine;
import org.xtext.example.statedsl.stateDSL.Transition;

@SuppressWarnings("all")
public class StateDSLSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private StateDSLGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == StateDSLPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case StateDSLPackage.AND_CONDITION:
				sequence_AndCondition(context, (AndCondition) semanticObject); 
				return; 
			case StateDSLPackage.CONDITION:
				sequence_LiteralCondition(context, (Condition) semanticObject); 
				return; 
			case StateDSLPackage.DOMAINMODEL:
				sequence_Domainmodel(context, (Domainmodel) semanticObject); 
				return; 
			case StateDSLPackage.OR_CONDITION:
				sequence_OrCondition(context, (OrCondition) semanticObject); 
				return; 
			case StateDSLPackage.STATE:
				sequence_State(context, (State) semanticObject); 
				return; 
			case StateDSLPackage.STATE_MACHINE:
				sequence_StateMachine(context, (StateMachine) semanticObject); 
				return; 
			case StateDSLPackage.TRANSITION:
				sequence_Transition(context, (Transition) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Condition returns AndCondition
	 *     OrCondition returns AndCondition
	 *     OrCondition.OrCondition_1_0 returns AndCondition
	 *     AndCondition returns AndCondition
	 *     AndCondition.AndCondition_1_0 returns AndCondition
	 *     PrimaryCondition returns AndCondition
	 *
	 * Constraint:
	 *     (left=AndCondition_AndCondition_1_0 right=PrimaryCondition)
	 * </pre>
	 */
	protected void sequence_AndCondition(ISerializationContext context, AndCondition semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, StateDSLPackage.Literals.CONDITION__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, StateDSLPackage.Literals.CONDITION__LEFT));
			if (transientValues.isValueTransient(semanticObject, StateDSLPackage.Literals.CONDITION__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, StateDSLPackage.Literals.CONDITION__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAndConditionAccess().getAndConditionLeftAction_1_0(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getAndConditionAccess().getRightPrimaryConditionParserRuleCall_1_2_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Domainmodel returns Domainmodel
	 *
	 * Constraint:
	 *     elements+=StateMachine+
	 * </pre>
	 */
	protected void sequence_Domainmodel(ISerializationContext context, Domainmodel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Condition returns Condition
	 *     OrCondition returns Condition
	 *     OrCondition.OrCondition_1_0 returns Condition
	 *     AndCondition returns Condition
	 *     AndCondition.AndCondition_1_0 returns Condition
	 *     PrimaryCondition returns Condition
	 *     LiteralCondition returns Condition
	 *
	 * Constraint:
	 *     name=ID
	 * </pre>
	 */
	protected void sequence_LiteralCondition(ISerializationContext context, Condition semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, StateDSLPackage.Literals.CONDITION__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, StateDSLPackage.Literals.CONDITION__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLiteralConditionAccess().getNameIDTerminalRuleCall_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Condition returns OrCondition
	 *     OrCondition returns OrCondition
	 *     OrCondition.OrCondition_1_0 returns OrCondition
	 *     AndCondition returns OrCondition
	 *     AndCondition.AndCondition_1_0 returns OrCondition
	 *     PrimaryCondition returns OrCondition
	 *
	 * Constraint:
	 *     (left=OrCondition_OrCondition_1_0 right=AndCondition)
	 * </pre>
	 */
	protected void sequence_OrCondition(ISerializationContext context, OrCondition semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, StateDSLPackage.Literals.CONDITION__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, StateDSLPackage.Literals.CONDITION__LEFT));
			if (transientValues.isValueTransient(semanticObject, StateDSLPackage.Literals.CONDITION__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, StateDSLPackage.Literals.CONDITION__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getOrConditionAccess().getOrConditionLeftAction_1_0(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getOrConditionAccess().getRightAndConditionParserRuleCall_1_2_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     StateMachine returns StateMachine
	 *     AState returns StateMachine
	 *
	 * Constraint:
	 *     (name=ID states+=AState+ transitions+=Transition* start=State)
	 * </pre>
	 */
	protected void sequence_StateMachine(ISerializationContext context, StateMachine semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AState returns State
	 *     State returns State
	 *
	 * Constraint:
	 *     name=ID
	 * </pre>
	 */
	protected void sequence_State(ISerializationContext context, State semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, StateDSLPackage.Literals.ASTATE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, StateDSLPackage.Literals.ASTATE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getStateAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Transition returns Transition
	 *
	 * Constraint:
	 *     (name=ID from=AState to=AState condition=Condition)
	 * </pre>
	 */
	protected void sequence_Transition(ISerializationContext context, Transition semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, StateDSLPackage.Literals.TRANSITION__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, StateDSLPackage.Literals.TRANSITION__NAME));
			if (transientValues.isValueTransient(semanticObject, StateDSLPackage.Literals.TRANSITION__FROM) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, StateDSLPackage.Literals.TRANSITION__FROM));
			if (transientValues.isValueTransient(semanticObject, StateDSLPackage.Literals.TRANSITION__TO) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, StateDSLPackage.Literals.TRANSITION__TO));
			if (transientValues.isValueTransient(semanticObject, StateDSLPackage.Literals.TRANSITION__CONDITION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, StateDSLPackage.Literals.TRANSITION__CONDITION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTransitionAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getTransitionAccess().getFromAStateParserRuleCall_5_0(), semanticObject.getFrom());
		feeder.accept(grammarAccess.getTransitionAccess().getToAStateParserRuleCall_8_0(), semanticObject.getTo());
		feeder.accept(grammarAccess.getTransitionAccess().getConditionConditionParserRuleCall_11_0(), semanticObject.getCondition());
		feeder.finish();
	}
	
	
}
