/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import com.google.inject.Inject;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
@SuppressWarnings("all")
public class StateDSLLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public StateDSLLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
}
