/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.statedsl.parser.antlr.internal.InternalStateDSLParser;
import org.xtext.example.statedsl.services.StateDSLGrammarAccess;

public class StateDSLParser extends AbstractAntlrParser {

	@Inject
	private StateDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalStateDSLParser createParser(XtextTokenStream stream) {
		return new InternalStateDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Domainmodel";
	}

	public StateDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(StateDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
