/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl.validation


import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class StateDSLValidator extends AbstractStateDSLValidator {
	
//	public static val INVALID_NAME = 'invalidName'
public static val INVALID_INHERITANCE = 'invalidINHERITANCE'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					StateDSLPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}



	
}
