/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl.tests;

import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import com.google.inject.Inject;

@ExtendWith(InjectionExtension.class)
@InjectWith(StateDSLInjectorProvider.class)
@SuppressWarnings("all")
public class StateDSLParsingTest {
  @Inject
  private /* ParseHelper<SystemRoot> */Object parseHelper;

  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field StateDSLParsingTest.parseHelper refers to the missing type SystemRoot"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
