/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl.generator;

import com.google.common.collect.Iterables;
import jakarta.inject.Inject;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.xtext.example.statedsl.stateDSL.AState;
import org.xtext.example.statedsl.stateDSL.State;
import org.xtext.example.statedsl.stateDSL.StateMachine;
import org.xtext.example.statedsl.stateDSL.Transition;

/**
 * Generates GDScript code from your model files on save.
 */
@SuppressWarnings("all")
public class StateDSLGenerator extends AbstractGenerator {
  @Inject
  @Extension
  private IQualifiedNameProvider _iQualifiedNameProvider;

  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    final StateMachine stateMachine = IterableExtensions.<StateMachine>head(Iterables.<StateMachine>filter(IteratorExtensions.<EObject>toIterable(resource.getAllContents()), StateMachine.class));
    if ((stateMachine == null)) {
      System.err.println("Error: No StateMachine found in the resource.");
      return;
    }
    boolean _isEmpty = stateMachine.getStates().isEmpty();
    if (_isEmpty) {
      String _name = stateMachine.getName();
      String _plus = ("Error: State machine \'" + _name);
      String _plus_1 = (_plus + "\' must have at least one state.");
      System.err.println(_plus_1);
      return;
    }
    String _string = this._iQualifiedNameProvider.getFullyQualifiedName(stateMachine).toString("/");
    String _plus_2 = (_string + ".gd");
    fsa.generateFile(_plus_2, 
      this.compileBase(stateMachine));
  }

  private CharSequence compileBase(final StateMachine machine) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("extends Node2D");
    _builder.newLine();
    _builder.append("class_name Base");
    _builder.newLine();
    _builder.newLine();
    _builder.append("var baseMachine: StateMachine = StateMachine.new()");
    _builder.newLine();
    _builder.append("@onready var base = $\"..\"");
    _builder.newLine();
    _builder.newLine();
    _builder.append("func _ready() -> void:");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("add_child(baseMachine)");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("baseMachine\\");
    _builder.newLine();
    {
      EList<AState> _states = machine.getStates();
      for(final AState state : _states) {
        {
          if ((state instanceof State)) {
            _builder.append("    ");
            _builder.append(".AddState(\"");
            String _name = ((State)state).getName();
            _builder.append(_name, "    ");
            _builder.append("\", ");
            String _name_1 = ((State)state).getName();
            _builder.append(_name_1, "    ");
            _builder.append(".new())\\");
            _builder.newLineIfNotEmpty();
          } else {
            if ((state instanceof StateMachine)) {
              _builder.append("    ");
              CharSequence _compile = this.compile(((StateMachine) state));
              _builder.append(_compile, "    ");
              _builder.newLineIfNotEmpty();
            }
          }
        }
        _builder.append("            ");
      }
    }
    _builder.append("\\");
    _builder.newLineIfNotEmpty();
    {
      EList<Transition> _transitions = machine.getTransitions();
      for(final Transition transition : _transitions) {
        _builder.append("    ");
        _builder.append(".AddTransition(\"");
        String _name_2 = transition.getFrom().getName();
        _builder.append(_name_2, "    ");
        _builder.append("\", \"");
        String _name_3 = transition.getTo().getName();
        _builder.append(_name_3, "    ");
        _builder.append("\", Callable(self, \"");
        String _name_4 = transition.getCondition().getName();
        _builder.append(_name_4, "    ");
        _builder.append("\"))\\");
        _builder.newLineIfNotEmpty();
        _builder.append("            ");
      }
    }
    _builder.append("\\");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append(".SetStart(\"");
    String _name_5 = machine.getStart().getName();
    _builder.append(_name_5, "    ");
    _builder.append("\")\\");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append(".Build()");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("baseMachine.Entry()");
    _builder.newLine();
    return _builder;
  }

  private CharSequence compile(final StateMachine machine) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append(".AddState(\"");
    String _name = machine.getName();
    _builder.append(_name);
    _builder.append("\", StateMachine.new()\\");
    _builder.newLineIfNotEmpty();
    {
      EList<AState> _states = machine.getStates();
      for(final AState state : _states) {
        {
          if ((state instanceof State)) {
            _builder.append("        ");
            _builder.append(".AddState(\"");
            String _name_1 = ((State)state).getName();
            _builder.append(_name_1, "        ");
            _builder.append("\", ");
            String _name_2 = ((State)state).getName();
            _builder.append(_name_2, "        ");
            _builder.append(".new())\\");
            _builder.newLineIfNotEmpty();
          } else {
            if ((state instanceof StateMachine)) {
              _builder.append("        ");
              Object _compile = this.compile(((StateMachine) state));
              _builder.append(_compile, "        ");
              _builder.newLineIfNotEmpty();
            }
          }
        }
        _builder.append("        ");
      }
    }
    _builder.append("\\");
    _builder.newLineIfNotEmpty();
    {
      EList<Transition> _transitions = machine.getTransitions();
      for(final Transition transition : _transitions) {
        _builder.append("        ");
        _builder.append(".AddTransition(\"");
        String _name_3 = transition.getFrom().getName();
        _builder.append(_name_3, "        ");
        _builder.append("\", \"");
        String _name_4 = transition.getTo().getName();
        _builder.append(_name_4, "        ");
        _builder.append("\", Callable(self, \"");
        String _name_5 = transition.getCondition().getName();
        _builder.append(_name_5, "        ");
        _builder.append("\"))\\");
        _builder.newLineIfNotEmpty();
        _builder.append("        ");
      }
    }
    _builder.append("\\");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append(".SetStart(\"");
    String _name_6 = machine.getStart().getName();
    _builder.append(_name_6, "        ");
    _builder.append("\")\\");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
}
