/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class StateDSLRuntimeModule extends AbstractStateDSLRuntimeModule {
}
