/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class StateDSLStandaloneSetup extends StateDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new StateDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
