/**
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl.stateDSL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.statedsl.stateDSL.AndCondition;
import org.xtext.example.statedsl.stateDSL.StateDSLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>And Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AndConditionImpl extends ConditionImpl implements AndCondition
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AndConditionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return StateDSLPackage.Literals.AND_CONDITION;
  }

} //AndConditionImpl
