/*
 * generated by Xtext 2.42.0
 */
package org.xtext.example.statedsl.scoping

import org.eclipse.emf.ecore.EReference
import org.eclipse.xtext.scoping.Scopes
import org.xtext.example.statedsl.stateDSL.StateMachine
import org.xtext.example.statedsl.stateDSL.Transition

class StateDSLScopeProvider extends AbstractStateDSLScopeProvider {

    def scope_Transition_from(Transition transition, EReference ref) {
        Scopes.scopeFor((transition.eContainer as StateMachine).states)
    }

    def scope_Transition_to(Transition transition, EReference ref) {
        Scopes.scopeFor((transition.eContainer as StateMachine).states)
    }

    def scope_StateMachine_start(StateMachine machine, EReference ref) {
        Scopes.scopeFor(machine.states)
    }
}
